# Generated by Django 2.2 on 2019-05-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190514_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profiles/None/default.png', upload_to='profiles'),
        ),
    ]
