# Generated by Django 2.2 on 2019-05-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190519_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/profiles/None/default.png', upload_to='profiles/'),
        ),
    ]
